module.exports = {
	darkMode: ["class", '[data-theme="dark"]'],
	content: [
		'./src/pages/**/*.{ts,tsx}',
		'./src/components/**/*.{ts,tsx}',
		'./src/app/**/*.{ts,tsx}',
	],
	safelist: [
		'bg-background',
		'text-text',
		'bg-primary',
		'bg-secondary',
		'bg-nav-bg',
		'text-link',
		'bg-accent',
		'text-success',
		'text-danger',
		'text-warning',
		'border-primary',
		'border-secondary',
		'border-background',
		'border-nav-bg',
		'border-success',
		'border-danger',
		'border-warning',
	],
	theme: {
		extend: {
			colors: {
				primary: 'var(--primary-color)',
				secondary: 'var(--second-color)',
				text: 'var(--text-color)',
				link: 'var(--link-color)',
				'link-accent': 'var(--link-color-accent)',
				nav: 'var(--nav-color)',
				'nav-bg': 'var(--nav-bg)',
				key: 'var(--key-color)',
				property: 'var(--property-color)',
				background: 'var(--bg-color)',
				'bg-accent': 'var(--bg-color-accent)',
				button: 'var(--button-color)',
				'theme-name': 'var(--theme-name-color)',
				success: 'var(--success)',
				danger: 'var(--danger)',
				warning: 'var(--warning)',
			},
		},
	},
	plugins: [
		require("tailwindcss-animate"),
		require("@tailwindcss/forms"),
	],
}
